### ISSUE TITLE
Photo: We couldn't find that photo

### ISSUE THREAD

**Issue by scips** [cuth/unsplash-wallpaper#18]
First of all, let me know that this tool is awesome, thanks for it.
I'm putting this issue here to discuss it, I'll propose a solution via a pull request if you find this is appropriate.

My use case:
I'm on ubuntu and I use a cron that call a shell script (to setup all the info needed to access the current wallpaper ubuntu service) that runs your script.
I change the picture every 5 minutes (night & day 24/7 ...)
So I have a lot of chance to come across an issue more than someone that run it manually daily.

This time I got the picture: https://images.unsplash.com/photo-1446704477871-62a4972035cd?fit=crop&fm=jpg&h=800&q=50&w=1200 (or a similar one, this one is from a random google image search)

So what would have been expected (from my point of view): to have an error that I can handle further on in my script

**Comment by cuth** [comment]
@scips, thanks! I totally agree. I couldn't figure out how to tell that was an error in the app but if you can figure that out, great!
