### ISSUE TITLE
Not an issue, just a script for Windows

### ISSUE THREAD

**Issue by cavo789** [cuth/unsplash-wallpaper#28]
Hello Jonathan, 

Thank you for your script : I'm using it since months.

For my easiness, I've write a very small Windows batch file for changing my wallpaper on every Windows startup. If the script can be usefull for you or anyone, you can found it here : https://github.com/cavo789/npm_unsplash_background

Thanks once again for your nice job 👍

**Comment by cuth** [comment]
👏 👏
