### ISSUE TITLE
In Linux doesn't change the background

### ISSUE THREAD

**Issue by rokity** [cuth/unsplash-wallpaper#3]
If I understood the goal of this module when I put "unsplash-wallpaper random" the script must set the desktop background with the image already downloaded through the "wallpaper" module .[link to module!](https://github.com/sindresorhus/wallpaper).
Why doesn't work on Ubuntu? or I don't understand the goal of this script?

**Comment by cuth** [comment]
Does it give you an error? I'd like to try to figure out how far it got through the script.

**Comment by rokity** [comment]
It doesn't give me an error , the script downloads the image but doesn't change the background. 
I have ubuntu Mate 15 and so there is mate environment. Maybe is this?

**Comment by cuth** [comment]
Would you mind installing [wallpaper-cli](https://github.com/sindresorhus/wallpaper-cli) to see if that works? If it does, then there is an issue with my code.

**Comment by rokity** [comment]
Nothing

**Comment by cuth** [comment]
Sorry, I can't help you. Please take the issue to [wallpaper](https://github.com/sindresorhus/wallpaper).
