### ISSUE TITLE
Automate random on Windows?

### ISSUE THREAD

**Issue by ginolon** [cuth/unsplash-wallpaper#4]
How to?

**Comment by cuth** [comment]
What terminal do you use on Windows? The regular command prompt, Powershell, Git Bash, Cygwin...?

**Comment by ginolon** [comment]
Makes it differences? I use Windows cmd.exe...

**Comment by cuth** [comment]
Just if you wanted to create an alias.

Run this command to save your preferences:

```
unsplash-wallpaper --save-config --width 1600 --height 1200
```

Then run this to get a random wallpaper

```
unsplash-wallpaper random
```

**Comment by ginolon** [comment]
Oh, sorry...

The real question is:

I need this `unsplash-wallpaper random` every hour on my Windows Desktop, but without Windows Command Prompt on Desktop every time.

How to task it as Windows Services?

**Comment by cuth** [comment]
Ah! Sorry, I don't know. There should be other packages that can run commands at certain times. This project isn't concerned with that.
