### ISSUE TITLE
Not Working on Windows

### ISSUE THREAD

**Issue by SaadeMotion** [cuth/unsplash-wallpaper#5]
How i use this on windows? Opening the js file doesn't work.
Where should i put the files in?

Sorry Newbie

**Comment by coderdiaz** [comment]
It's works. You only need install [NodeJS ](https://nodejs.org/dist/v4.4.3/node-v4.4.3-x64.msi) with NPM in your computer. After, you only need open a console and enter `npm install -g unsplash-wallpaper`.

Greetings.
