### ISSUE TITLE
Is it possible to get unsplash.com/photos/ ?

### ISSUE THREAD

**Issue by sahrechiiz** [cuth/unsplash-wallpaper#6]
Thanks. It works perfectly.
One thing is that is it possible not just get images from unsplash.it/images but also unsplash.com/photos/ ?

**Comment by tintin099** [comment]
I've found an inspired tool a couple of days ago, it seems a good alternative who uses *unsplash api* ([splash-cli](httpsgithub.com/rawnly/splash-cli)). Also it is continuously updated.

Sorry @sahrechiiz but you don't release an update from nov 2015..

**Comment by cuth** [comment]
I've switched from `unsplash.it` to `source.unsplash.com` in version 5.
