### ISSUE TITLE
How about changing wallpapers daily?

### ISSUE THREAD

**Issue by inancgumus** [cuth/unsplash-wallpaper#8]
I can add a support to change the wallpapers for the configured timespan, for example, starting with daily?

**Comment by cuth** [comment]
So then the app needs to continue running at all times? If so, that seems out of scope of what I want this app to do but feel free to fork and publish a new app like `usplash-wallpaper-daily`.

**Comment by inancgumus** [comment]
Allright.

**Comment by fakeYanss** [comment]
@inancgumus you can create a .bat file and make it run when system startup. And the .bat file is 
`unsplash-wallpaper -r`
